### PR TITLE
Fixed sidebar issues

### LINKED ISSUE #424: Fix sidebar and top nav bar issues on home page

### PR DESCRIPTION
**Pull request by Janvi-Thakkar**
## Description
- Added login signup buttons in the sidebar for unauthorized small screen users
- Added conditions for tutorials and my profile section to appear only when the user is authorized
- Logout will only appear when the user is logged in
- Removed the app-bar button from the top navigation bar.

## Related Issue
Fixes #424 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: functions/auth.js [hunk 1]
```diff
@@ -3,7 +3,7 @@ const admin = require("firebase-admin");
 const serviceAccount = require("./private/cl-dev-pk.json");
 admin.initializeApp({
   credential: admin.credential.cert(serviceAccount),
-  databaseURL: process.env.REACT_APP_DATABASE_URL,
+    databaseURL: "https://codelabz-58d31-default-rtdb.asia-southeast1.firebasedatabase.app",
```
Comment (Niweera) [inline functions/auth.js:6]: it's better to keep this take from env variables.

Comment (Janvi-Thakkar) [reply functions/auth.js]: By mistake, I committed it! Updated in the new commit

**Review by Niweera — APPROVED** [review]

**Review by shahaab — APPROVED** [review]

**Review by sakkshm26 — APPROVED** [review]

**Review by IITvamp — APPROVED** [review]

**Review by Maahi10001 — APPROVED** [review]
