### PR TITLE
tutorial page bug

### LINKED ISSUE #140: Bug in tutorial page
**Describe the bug**
I found a bug in tutorial page , here I have two org test and test5 , so in the gif you can notice that automatically all the organization get selected on their own , I cant choose specific org on my own. I'll open a pr after fixing them.

**To Reproduce**
1. create more than one org
2. go to tutorial page from navbar
 
**Expected behavior**
We can specifically access a particular organization on our own
**Screenshots**
simplescreenrecorder-2021-07-06_17 08 07

### PR DESCRIPTION
**Pull request by rijusougata13**
tutorial page bug
## Description

fixed bug in tutorial page
## Related Issue

fixed #140 

## How Has This Been Tested?

with npm
## Screenshots or GIF (In case of UI changes):
simplescreenrecorder-2021-07-06_17 50 48

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by rijusougata13** [comment]
@shehand  as in previous PR we found that after gitignoring config file it stills appear in PRs . so I tried googling it and found a solution saying that git still tracking that config file , and it can be solved by this command 
```
git rm -r --cached src/config/index.js 
```
It succesfully worked now if i make some changes in that file git isn't tracking this file . but in this following PR I found that following config file is gone . what should I do ?

File: src/components/Tutorials/MyTutorials/BaseTutorialsComponent/TutorialCard.js [hunk 1]
```diff
@@ -23,7 +23,7 @@ const TutorialCard = ({
           image={
             icon
               ? icon
-              : 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png'
+              : "https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png"
```
Comment (shehand) [inline src/components/Tutorials/MyTutorials/BaseTutorialsComponent/TutorialCard.js:26]: Better if we can add this to local assets. Not sure what would happen in the future to the image in the URL

**Review by shehand — APPROVED** [review]

File: src/components/Tutorials/MyTutorials/BaseTutorialsComponent/TutorialCard.js (hunk 1 above)
Comment (rijusougata13) [reply src/components/Tutorials/MyTutorials/BaseTutorialsComponent/TutorialCard.js:26]: okay I am moving this to assets folder.

**Review by Niweera — APPROVED** [review]
